# Generated by Django 2.2 on 2020-12-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopulationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
                ('code', models.IntegerField()),
                ('year', models.IntegerField()),
                ('population', models.FloatField()),
                ('region', models.CharField(max_length=20)),
            ],
        ),
    ]
