# Generated by Django 2.2 on 2020-12-20 04:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataloader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='populationdata',
            name='region',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None),
        ),
    ]
