# Generated by Django 2.2 on 2020-12-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataloader', '0003_auto_20201220_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='populationdata',
            name='country',
            field=models.CharField(max_length=50),
        ),
    ]
