# Generated by Django 2.2 on 2020-12-20 08:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataloader', '0005_auto_20201220_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='populationdata',
            name='group',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=None),
        ),
    ]
