# Generated by Django 2.2 on 2020-12-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataloader', '0006_auto_20201220_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_group', models.CharField(max_length=100)),
                ('Population_datas', models.ManyToManyField(to='dataloader.PopulationData')),
            ],
            options={
                'ordering': ['country_group'],
            },
        ),
    ]
