# Generated by Django 2.2 on 2020-12-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataloader', '0007_countrygroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrygroup',
            name='Population_datas',
        ),
        migrations.RemoveField(
            model_name='populationdata',
            name='group',
        ),
        migrations.AddField(
            model_name='populationdata',
            name='group',
            field=models.ManyToManyField(to='dataloader.CountryGroup'),
        ),
    ]
